# Generated by Cloud66 Starter
FROM node:6.1.0

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# ADD CUSTOM REGISTRY HERE IF REQUIRED
RUN npm config set strict-ssl false
RUN npm config set proxy $CUSTOM_REGISTRY
RUN npm config set https-proxy $CUSTOM_REGISTRY

ADD . $APP_HOME
RUN npm install

